#!/usr/bin/env bash
# Start OlympusRelay
# Generated by setup.sh
cd "/mnt/c/Users/Sean/Documents/olympusrepo"
source .venv/bin/activate 2>/dev/null || true
set -a; source .env 2>/dev/null; set +a
exec olympusrelay --port 9000 --id "HughJanus-relay"
